apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: regulus-maximus
  namespace: tsm
  labels:
    team: tsm
    system: mottak

spec:
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        name: regulus-maximus-instance
        cascadingDelete: false
        databases:
          - name: regulus-maximus
            envVarPrefix: DB
            users:
              - name: bigquery
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
        flags:
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: "write,ddl,role"
          - name: pgaudit.log_parameter
            value: "on"
          - name: cloudsql.logical_decoding
            value: "on"
        pointInTimeRecovery: true
        tier: db-custom-1-3840
        autoBackupHour: 4
        maintenance:
          day: 1
          hour: 5

  kafka:
    pool: nav-prod

  port: 8080
  replicas:
    min: 1
    max: 10
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 30m
      memory: 512Mi

  liveness:
    path: /internal/health/alive
  readiness:
    path: /internal/health/ready
  preStopHook:
    http:
      path: /internal/shutdown
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java

  # Used to authorize /admin endpoints with Entra AD OBO-tokens
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: false
      claims:
        groups:
          # EntraAD: nais-team-tsm (developers - same as Zara uses)
          - id: '35c70ac7-e8e6-4cec-933b-86106a97c0d4'

  accessPolicy:
    inbound:
      rules:
        - application: zara
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: tsm-pdl-cache
