apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: regulus-maximus
  namespace: tsm
  labels:
    team: tsm
    system: mottak
  annotations:
    texas.nais.io/enabled: "true"
spec:
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        name: regulus-maximus-instance
        cascadingDelete: false
        databases:
          - name: regulus-maximus
            envVarPrefix: DB
            users:
              - name: bigquery
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
        flags:
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: "write,ddl,role"
          - name: pgaudit.log_parameter
            value: "on"
          - name: cloudsql.logical_decoding
            value: "on"
        pointInTimeRecovery: true
        tier: db-custom-1-3840
        autoBackupHour: 4
        maintenance:
          day: 1
          hour: 5
    buckets:
      - name: regulus-maximus-bucket-prod
  image: {{ image }}
  replicas:
    min: 1
    max: 10
  port: 8080
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    path: /internal/health
    initialDelay: 60
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 512Mi
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: tsm-pdl-cache
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
