apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: regulus-maximus
  namespace: tsm
  labels:
    team: tsm
    system: mottak
  annotations:
    texas.nais.io/enabled: "true"
spec:
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        name: regulus-maximus-instance
        cascadingDelete: false
        databases:
          - name: regulus-maximus
            envVarPrefix: DB
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
        pointInTimeRecovery: true
        tier: db-custom-1-3840
  image: {{ image }}
  replicas:
    min: 1
    max: 3
    scalingStrategy:
      kafka:
        consumerGroup: regulus-maximus
        threshold: 100
        topic: tsm.sykmeldinger-input
  port: 8080
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    path: /internal/health
    initialDelay: 60
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  secureLogs:
    enabled: false
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: tsm-pdl-cache
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
