apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: regulus-maximus
  namespace: tsm
  labels:
    team: tsm
    system: mottak

spec:
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        name: regulus-maximus-instance
        cascadingDelete: false
        databases:
          - name: regulus-maximus
            envVarPrefix: DB
            users:
              - name: bigquery
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
        flags:
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: "write,ddl,role"
          - name: pgaudit.log_parameter
            value: "on"
          - name: cloudsql.logical_decoding
            value: "on"
        pointInTimeRecovery: true
        tier: db-f1-micro

  kafka:
    pool: nav-dev

  port: 8080
  replicas:
    min: 1
    max: 1
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 25m
      memory: 600Mi

  liveness:
    path: /internal/health/alive
  readiness:
    path: /internal/health/ready
  preStopHook:
    http:
      path: /internal/shutdown
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  envFrom:
    - configmap: regulus-behandlingsdager
  # Used to authorize /admin endpoints with Entra AD OBO-tokens
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: true

  accessPolicy:
    inbound:
      rules:
        - application: zara
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: tsm-pdl-cache
