spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_database
    username: my_user
    password: my_password
  flyway:
    url: jdbc:postgresql://localhost:5432/my_database
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092
    security:
      protocol: plaintext
server:
  port: 8080
