ktor {
  deployment {
    port = 8080
    shutdownTimeout = 15000
  }
  application {
    modules = [no.nav.tsm.ApplicationKt.module]
  }
}

postgres {
  # Used to allow setting the DB url locally
  url = "postgresql://localhost:7967/regulus-maximus"
  url = ${?DB_URL}
  jdbc = "jdbc:"${postgres.url}
  r2dbc = {
    url = "r2dbc:"${postgres.url}
  }
  username = "user"
  username = ${?DB_USERNAME}
  password = "password"
  password = ${?DB_PASSWORD}
}

kafka {
  config {
    "bootstrap.servers" = "localhost:9092"
    "bootstrap.servers" = ${?BOOTSTRAP_SERVERS}
    "security.protocol" = "PLAINTEXT"
  }
  sykmeldingInputConsumer {
    longPoll: PT10S
  }
}

app {
  name = "local-pod"
  name = ${?POD_NAME}
  runtime = "local"
}
