spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/my_database
    username: my_user
    password: my_password
  flyway:
    url: jdbc:postgresql://localhost:5432/my_database
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: none
      enable-auto-commit: true
  sql:
    init:
      mode: always
server:
  port: 8080
