spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  user: ${spring.r2dbc.username}
  password: ${spring.r2dbc.password}
  baseline-on-migrate: true
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
    application:
      name: regulus-maximus
  kafka:
    bootstrap-servers: localhost:9092
    group-id: regulus-maximus
    topics:
      mottatt-sykmelding: tsm.mottak-sykmelding
      sykmelding-med-utfall: tsm.mottak-sykmelding-med-utfall
    consumer:
      max-poll-records: 1
      auto-offset-reset: none
      enable-auto-commit: false
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
