ktor:
  environment: local
  development: true
  application:
    modules:
      - no.nav.tsm.mottak.ApplicationKt.module
      - no.nav.tsm.mottak.dev_tools.DevToolsKt.devTools
  deployment:
    port: 8080
  database:
    dbUser: postgres
    dbPassword: postgres
    dbHost: localhost
    dbPort: 5432
    dbName: postgres
  kafka:
    config:
      bootstrap.servers: "localhost:9092"
