ktor {
  deployment {
    port = 8080
    shutdownTimeout = 15000
  }
  application {
    modules = [no.nav.tsm.ApplicationKt.module]
  }
}

postgres {
  jdbc = ${DB_JDBC_URL}
  r2dbc = {
    url = "r2dbc:postgresql://"${DB_HOST}":"${DB_PORT}"/"${DB_DATABASE}"?sslRootCert="${DB_SSLROOTCERT}"&sslMode=verify-ca"
    sslCert = ${DB_SSLCERT}
    sslKeyPk8 = ${DB_SSLKEY_PK8}
  }
  username = ${DB_USERNAME}
  password = ${DB_PASSWORD}
}

behandlingsdager {
  ids = ${BEHANDLINGSDAGER_IDS}
}

app {
  name = ${NAIS_POD_NAME}
}
