spring:
  datasource:
    url: "${DB_JDBC_URL}"
    username: ${db.username}
    password: ${db.password}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 1
  flyway:
    enabled: true
    user: ${db.username}
    password: ${db.password}
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: "${DB_JDBC_URL}"
  application:
    name: regulus-maximus
  kafka:
    bootstrap-servers: ${kafka.brokers}
    security:
      protocol: ssl
    ssl:
      trust-store-location: file:${kafka.truststore.path}
      trust-store-type: JKS
      trust-store-password: ${kafka.credstore.password}
      key-store-location: file:${kafka.keystore.path}
      key-store-type: PKCS12
      key-store-password: ${kafka.credstore.password}
    topics:
      sykmeldinger-input: tsm.sykmeldinger-input
      sykmeldinger-output: tsm.tsm-sykmeldinger
management:
  endpoint:
    prometheus.enabled: true
    health.probes.enabled: true
    health.show-details: always
  endpoints.web:
    base-path: "/internal"
    exposure.include: health, prometheus
  health:
    livenessstate.enabled: true
    readinessState.enabled: true

nais:
  cluster: ${NAIS_CLUSTER_NAME}
  texas:
    endpoint: ${NAIS_TOKEN_ENDPOINT}

tsm:
  pdl:
    service: tsm.tsm-pdl-cache
    url: http://tsm-pdl-cache
