name: Build and deploy
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    name: Build,push and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 21
        uses: nais/docker-build-push@v0
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/nais-prod.yaml
          VAR: image=${{ needs.build.outputs.image }}
      - name: build artifact
        run: ./gradlew shadowJar
      - name: Push docker image to GAR
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: tsm
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

